### ISSUE TITLE
apktool error

### ISSUE THREAD

**Issue by danny4049** [kefir500/apk-icon-editor#18]
hi im using the latest version of the apk icon editor...ive tried to change app names and when i want to repack it it show apktool error....what am i doing wrong here...pls help

**Comment by kefir500** [comment]
Hi, could you please send here the contents of the logfile located at **%LOCALAPPDATA%\apk-icon-editor\apk-icon-editor.log** (after repeating steps to cause this error)?

**Comment by kefir500** [comment]
Try the [newest](https://github.com/kefir500/apk-icon-editor/releases/latest) version, it supports the latest Apktool.
Closing the issue due to inactivity.
If your problem is still unsolved, reopen this issue.
