### ISSUE TITLE
Main Bug!

### ISSUE THREAD

**Issue by KashisHrishikesh** [kefir500/apk-icon-editor#21]
It decompiles the APK very easily, I'm able to change its icon and name also very easily. But then, it is not able to pack the APK. There is no use if it can't repack the APK. Please fix it.

**Comment by kefir500** [comment]
Please provide the logfile contents located at **%LOCALAPPDATA%\apk-icon-editor\apk-icon-editor.log**

**Comment by kefir500** [comment]
According to the logfile you've just emailed me, your **Java** is installated improperly (the error reads: `could not find java.dll`). Reinstall JRE.

**Comment by KashisHrishikesh** [comment]
Can you send me a proper link from where should I install it because while
installing your application, I remember installing Java too.

**Comment by kefir500** [comment]
* **Completely** remove your currently installed Java.
* Download [JRE](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) or [JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).
* Also check your `JAVA_HOME` environment variable.

Google for `"could not find java.dll"`, there are many advices on fixing the improperly installed Java.

**Comment by KashisHrishikesh** [comment]
I tried my best but I'm sorry to tell you it's not able to even unpack apk
now.

**Comment by kefir500** [comment]
Well, the issue is not "APK Icon Editor" but the improperly installed Java on your machine. This issue tracker covers only problems of the first type.
