### ISSUE TITLE
ApkTool error

### ISSUE THREAD

**Issue by Legosrock** [kefir500/apk-icon-editor#22]
Hi, When trying to open a certain apk, It opens fine in QuaziZip mode, but trying to open it in apktool mode gives and apktool error. Thanks for your help. the log is:

[18:13:16] APK Icon Editor v1.2.0 
[18:13:16] Initializing... 
[18:13:26] "JRE" 32-bit found: 
[18:13:26] "java version "1.8.0_40"

Java(TM) SE Runtime Environment (build 1.8.0_40-b25)

Java HotSpot(TM) Client VM (build 25.40-b25, mixed mode, sharing)" 
[18:13:26] "JDK" 32-bit not found! 
[18:13:26] Language set to "en" 
[18:13:28] Unpacking "C:\Users\Andrea\Desktop\Go Sms Pro Premium 6.2 build 241.apk" 
[18:13:29] Starting...
 
[18:13:31] aapt exit code: 0 
[18:13:56] Unpacked in 18.615s 
[18:13:56] "Cleaning up unclosed ZipFile for archive C:\Users\Andrea\apktool\framework\1.apk

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=splitMotionEvents, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=animateLayoutChanges, value=0xffffffff

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=splitMotionEvents, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

W: Could not decode attr value, using undecoded value instead: ns=android, name=textCursorDrawable, value=0x00000000

Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101035b

	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)

	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:59)

	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:55)

	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:60)

	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)

	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:553)

	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:309)

	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:116)

	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)

	at brut.apktool.Main.cmdDecode(Main.java:169)

	at brut.apktool.Main.main(Main.java:85)

" 
[18:13:56] Error (Apktool Error): Apktool Error

**Comment by kefir500** [comment]
Hi,
Could you please [email](mailto:kefir500@gmail.com) me the APK you are trying to repack?
I'll see what I can do.

**Comment by Legosrock** [comment]
Ok, I emailed it to you.

**Comment by kefir500** [comment]
Repacking goes fine on my machine.
Try deleting **C:\Users\%USERNAME%\apktool\framework\1.apk** and then repack your APK again.

**Comment by Legosrock** [comment]
Thank you so much, that fixed it.
