### ISSUE TITLE
Interesting feature

### ISSUE THREAD

**Issue by ZeeSteen** [kefir500/apk-icon-editor#27]
Hi guys,

I just wanted to let you guys know it could be interesting to implement a command line interface. This way people can write a script they can execute.

For example I'm currently developing an application and it's HELL to change the default icon, honestly, it's horrible :p! What I'd love to be able to do is write a script for APK icon editor that launches when I finish a build so I don't have to manually change the icons ^_^

Kind regards

**Comment by kefir500** [comment]
Hi,

By and large, "APK Icon Editor" is a tool implementing GUI for the command line utility called [Apktool](https://ibotpeaches.github.io/Apktool). Have you tried using it?

**Comment by ZeeSteen** [comment]
Owh! I did not know that! Thank you. I'll give it a try!
