### ISSUE TITLE
Logo and name not changing

### ISSUE THREAD

**Issue by Lightiam** [kefir500/apk-icon-editor#33]
Nothing happens after changing the name and the logo, the original name and logo show when I install it. It also ask for Google permission.

How can I use for a personal demo with any key or restrictions?

**Comment by kefir500** [comment]
Provide the following information:
- Logfile (repack your APK and press <kbd>Ctrl</kbd>+<kbd>L</kbd>).
- Title of your device.
- Name and version of the original APK.
- Did you uninstall the original APK before installing the modded one?

**Comment by Lightiam** [comment]
1. Logfile (repack your APK and press Ctrl+L). -[apk log file.docx](https://github.com/kefir500/apk-icon-editor/files/121327/apk.log.file.docx)
2. Title of your device - Note 3 Samsung SM- N900
Android 5 
3.  Version name is RoadYO Taxi , version 2.2.7
4. I uninstalled

**Comment by kefir500** [comment]
Checked on multiple devices, everything works fine with both repacking methods – `ZIP` and `Apktool`. Do you mean the icon of the application or the splash screen logo?

**Comment by Lightiam** [comment]
The Icon and the name did not change. can you change it and send me the APK for a test?

**Comment by kefir500** [comment]
Contact me directly via email (see my [profile](https://github.com/kefir500)), I will send you some tests. Also, note that there is **no** packing process in your logfile, only unpacking.

**Comment by kefir500** [comment]
As I already wrote in the email,

- Probably the old icons are cached on your device. Try restarting it or clearing the icon cache.
- Increase the version code value in the APK Icon Editor `Properties` tab while in the `Apktool` mode: this should force the icon cache update.

The provided APK was successfully repacked and checked on multiple devices and operating systems including Android, Amazon Fire OS and BlackBerry 10.

Closing the issue.

**Comment by Lightiam** [comment]
Hello Alexander, The APK provide did not work, but if you can help me do one, I will pay for it as I need it for a demo ASAP.//Bola                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Alexander GorishnyakSent: Thursday, February 11, 2016 1:07 PMTo: kefir500/apk-icon-editorReply To: kefir500/apk-icon-editorCc: LightiamSubject: Re: [apk-icon-editor] Logo and name not changing (#33)As I already wrote in the email,


Probably the old icons are cached on your device. Try restarting it or clearing the icon cache.
Increase the version code value in the APK Icon Editor Properties tab while in the Apktool mode: this should force the icon cache update.


The provided APK was successfully repacked and checked on multiple devices and operating systems including Android, Amazon Fire OS and BlackBerry 10.

Closing the issue.

—Reply to this email directly or view it on GitHub.

**Comment by kefir500** [comment]
Do you use this APK on your *BlackBerry* device? Although you can change the icon and title of this application, it still requires **Google Services**. Both *BlackBerry* and *Amazon Kindle* devices don't support this feature, so this problem has nothing to do with *APK Icon Editor*.

**Comment by Lightiam** [comment]
Yes, I did install on my BlackBerry. Can you do anyone for me? Am willing to pay.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Alexander GorishnyakSent: Thursday, February 11, 2016 1:56 PMTo: kefir500/apk-icon-editorReply To: kefir500/apk-icon-editorCc: LightiamSubject: Re: [apk-icon-editor] Logo and name not changing (#33)Do you use this APK on your BlackBerry device? Although you can change the icon and title of this application, it still requires Google Services. Both BlackBerry and Amazon Kindle devices don't support this feature, so this problem has nothing to do with APK Icon Editor.

—Reply to this email directly or view it on GitHub.

**Comment by kefir500** [comment]
I am not an Android/BlackBerry developer. You better look for one on the thematic resources, not on this issue tracker.
