### ISSUE TITLE
Source code doesn't compile under Linux

### ISSUE THREAD

**Issue by monkiki** [kefir500/apk-icon-editor#37]
Hi, I've tried to compile the source under Linux Mint  17.3 (which is base on Ubuntu 14.04) but it fails:

core/application.h:22:50: error: ‘QMessageLogContext’ does not name a type
     static void msgHandler(QtMsgType type, const QMessageLogContext &, const QString &msg);
                                                  ^
core/application.h:22:69: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
     static void msgHandler(QtMsgType type, const QMessageLogContext &, const QString &msg);

Any tip? Thanks.

**Comment by kefir500** [comment]
Hi, seems that you are using **Qt4** instead of **Qt5**.

**Comment by monkiki** [comment]
I have both Qt4 and Qt5 installed. Would you mind pointing me to the Linux compilation instructions? Perhaps I missed any step.

**Comment by kefir500** [comment]
If you are using QtCreator, make sure that the needed Qt5 version is listed under the `Tools` --> `Options` --> `Build & Run` --> `Qt Versions` menu. Also, check the `Kits` tab in the same dialog:

- If Qt5 is **present**, select it in the `Projects` tab which is located on the left pane of the main window.
- If Qt5 is **not present**, add the qmake version manually and create the corresponding kit under the aforementioned `Build & Run` tabs.

If this does not help, try setting these environment variables:

- `QT_SELECT=qt5`
- `QTDIR=$QT5` where `$QT5` is the path to your Qt5 installation.

**Comment by monkiki** [comment]
I will try compiling with QtCreator. Thanks.

**Comment by kefir500** [comment]
If you are manually using `qmake`, see the section about environment variables in my previous message. Also, you may simply specify the absolute path to the needed `qmake` version.

**Comment by monkiki** [comment]
Now I've another error:

core/keys.h:13:2: error: #error The following variables are dummies. Set your own values and/or remove this line.
 #error The following variables are dummies. Set your own values and/or remove this line.

**Comment by kefir500** [comment]
That's not an error, that's just a security warning.
Those private constants are used for encrypting passwords.

As noted in the message,
> Set your own values and/or **remove this line**.

So, simply remove that `#error` line from the `src/core/keys.h` file.

**Comment by monkiki** [comment]
After commenting the line, another error appears:

/usr/bin/ld: /opt/apk-icon-editor-1.6.0/src/../lib/bin/libquazip.a(unzip.o): undefined reference to symbol 'inflateInit2_'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/linux/apk-icon-editor] Error 1

**Comment by kefir500** [comment]
Try one of the following:
- Add `LIBS += -lz` line to the `src/apk-icon-editor.pro`.
- Add `LIBS += -L<path>` to the `src/apk-icon-editor.pro`. Note that `<path>` should point to the `libz.so` library. I don't know where this library is located on your machine, that is why I cannot make further assumptions.

**Comment by monkiki** [comment]
Great! Now compiles in my Linux box!

I think you should fix this in the source code and add any text document explaining the possible issues and solutions.

Thanks!

**Comment by kefir500** [comment]
The required library `libz.so` can be located in many different places for different distributions; there is no universal recipe for Linux, I guess. Anyway, I'll see what I can do in order to ease the compilation pain on Linux :)

Don't forget that you will also need third-party Android tools like [`aapt`](https://github.com/android/platform_prebuilt/raw/master/sdk/tools/linux/aapt), [`zipalign`](https://github.com/android/platform_prebuilt/raw/master/sdk/tools/linux/zipalign), and `signapk.jar`. I will add these files to the repo in the near future (one or two days), just wait a bit.

Thank you for your cooperation!

**Comment by monkiki** [comment]
Thanks a lot!
