### ISSUE TITLE
Ability to change package name

### ISSUE THREAD

**Issue by kefir500** [kefir500/apk-icon-editor#42]
APK Icon Editor needs the ability to **change package name via graphical user interface**. Currently the package name can be changed only through the manual editing of the unpacked internal files (Apktool mode).

**Comment by lastblade** [comment]
agreed

**Comment by ibuprophen1** [comment]
Changing the Package Name (Installation Directory Structure) isn't always an easy thing to do and its complexity (how much work would be involved) all depends upon the complexity of the app that it's being performed on. 

Some apps are as simple as changing the Package Name, typically, located at the top of the AndroidManifest.xml file, some not only require that same step but, also requires additional work within 1 or more other areas within the structure and, in some cases, just can't be effectively done for various reasons. 

To extend this feature within the APK Icon Editor would require allot of work for the developer and I don't know of any same/similar software that will perform this specific task as a part of its function.

No matter what software you use, to Decompile/Recompile an app, changing the Package Name will always require manual intervention within the Decompiled App. 

The APK Icon Editor does have 3 Unique qualities that does stand out from the other similar software. This is the easy way to change an apps Icon, Name, Version Number and Build Number without requiring to having to manually do  so. 

I hope that I had explained this okay via text... :-) 

~Ibuprophen

**Comment by F3000** [comment]
So with that tool it is not possible to modify any apk to install it twice on the same device ?

**Comment by kefir500** [comment]
@F3000 For now there is no automated way to perform it in APK Icon Editor, however you can try this manually as a temporary solution:
- Enable **Apktool** mode.
- Enable **Decompile CLASSES.DEX** in the "Settings" –> "Repacking" (<kbd>Ctrl</kbd> + <kbd>P</kbd>) dialog.
- Open APK.
- Click "File" –> "**Explore APK Contents**" (<kbd>Ctrl</kbd> + <kbd>D</kbd>).
- Follow [this tutorial](https://forum.xda-developers.com/showthread.php?t=2760965) to change the package name. In fact, it all comes down to changing the directory structure to reflect the new package name and replacing the corresponding occurrences in files.

**Comment by F3000** [comment]
Thanks for the tip . I will try this :)

**Comment by ibuprophen1** [comment]
I was just wondering about some feedback from anyone who may have tried/tested this feature on the latest version of the Software... :-)

**Comment by kefir500** [comment]
@ibuprophen1 Maybe I didn't understand you, but this feature is not implemented in APK Icon Editor yet.

**Comment by ibuprophen1** [comment]
I can't believe this one...

I am looking at this issue and completely thinking of something else! 

I must be suffering from HCS (Having Children Syndrome)!!! LOL... :-) 

Sorry about this one @kefir500... :-)

**Comment by kmwit** [comment]
hi, newbie here, working on an app and it is open source (no idea how to compile, there are two apps created by the same company for the same service, one app opened edited and repackaged ok, second app open, not touched, tried repacking and error. I can only assume its something to do with the xml as it the files it mentions org.app_name.com or similar. I have the error code
[apkiconeditor-error.txt](https://github.com/kefir500/apk-icon-editor/files/2365430/apkiconeditor-error.txt)
Need some help as I have tried all of the above, PS enable apktool mode??? can not find on this program.

**Comment by kefir500** [comment]
@kmwit  
Please, create a [new issue](https://github.com/kefir500/apk-icon-editor/issues/new) since this one is focused on adding a new feature.  
Also, provide a full log:
- Repeat the steps until you get this error;
- Click `Help` --> `Logs` --> `Open Log Directory` (or simply press <kbd>Ctrl</kbd>+<kbd>L</kbd>);
- Attach the log to the reply.

**Comment by kefir500** [comment]
Implemented in [APK Editor Studio](https://qwertycube.com/apk-editor-studio/).
