### ISSUE TITLE
Remove private keys

### ISSUE THREAD

**Issue by strazzere** [kefir500/apk-icon-editor#5]
<<
https://github.com/kefir500/apk-icon-editor/tree/master/setup/contents/signer
>>

These keys should not be distributed for usage as the concept of "private" keys is compromised. This results in the authors identity to no be trusted and can be misused my malicious developers. This also opens up users to upgrade attacks.

I've already spotted plenty of malicious developers using this key - it should be removed and replaced with instructions for users of apk-icon-editor to sign things _properly_.

**Comment by kefir500** [comment]
KeyStore creation wizard was implemented in [APK Icon Editor 1.2.0].
The aforementioned private key remained untouched (acting just like a test dummy), as long as warning of its insecurity.
