### ISSUE TITLE
It helps to be able to modify the source code like java

### ISSUE THREAD

**Issue by xoceunder** [kefir500/apk-icon-editor#59]
It helps to be able to modify the source code like java

**Comment by kefir500** [comment]
When APK Icon Editor is used in Apktool mode (*Settings* –> *Repacking* –> *Use Apktool repacking*), Java classes are decompiled into `smali` files. You can edit them as you wish (*File* –> *Explore APK Contents* or simply press <kbd>Ctrl</kbd> + <kbd>D</kbd>) and then pack the APK back.

**Comment by xoceunder** [comment]
I'm creating an error I want to be able to decompile to edit and edit from android studio since I paid for the apk and they only sent me the apk file and not the source code could you help me see how I can rescue my lost money

**Comment by kefir500** [comment]
Unfortunately, there is no way do it via APK Icon Editor.  
However, you can search for more info on your question [here](https://stackoverflow.com/questions/3593420/is-there-a-way-to-get-the-source-code-from-an-apk-file).
