### ISSUE TITLE
Apk tool Error , Warning: QPixmap::scaled: Pixmap is a null pixmap , this APK Does Not Support Current DPI

### ISSUE THREAD

**Issue by egymummy** [kefir500/apk-icon-editor#61]
Hello Alexander ,
First All Due Respects And Thanks For An Awesome Tool We Got in Here
i Have Been Using APK Tools For A while , Never Had an Issue
i am working on an APK
when Open with Zip Method it opens correctly Icons are in Place and Can Be changed and res Folder is Editable , ( Of Course No Full De compile ) ( No values Folders ) (No Strings.xml ) but it is OK as We all Know That Zip Method is A simple Method To Change Icons And Drawable Mainly

But when i Open with APKtools Method , The Icons Become Blank and There is No way to Edit anything
Tried To Edit an icon ( which is Not found Anyway)
it Gives Error 
this APK Does Not Support Current DPI

Note***
Even if i Just Unpack and Have Not Changed anything And try to Repack it again , it gives The Following error
Apk tool Error  ( run-time error)

I noticed something in The Log File
 Warning: QPixmap::scaled: Pixmap is a null pixmap , 

This Happens Only When APK Tool Method Which is Important As it Gives More Options To Edit and Play Around With The APP

Help is Appreciated
Contact me
Egymummy@gmail.com

Here is The LOG

[07:16:04.611] APK Icon Editor v1.7.1 
[07:16:04.611] Initializing... 
[07:16:04.611] Starting...
 
[07:16:04.627] Screen DPI: 96 
[07:16:04.674] Language set to "en" 
 
[07:16:04.705] Unpacking "C:\Users\Asus\Desktop\super apk\Russia2018.apk" 
[07:16:04.705] Using Apktool: true 
[07:16:04.705] Output directory: "C:\Users\Asus\AppData\Local\Temp/apk-icon-editor/" 
[07:16:05.214] aapt exit code: 0 
[07:16:05.214] 
--- DUMP START ---
 package: name='Russia.2018' versionCode='10' versionName='4.1.5' platformBuildVersionName=''
sdkVersion:'17'
targetSdkVersion:'26'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
application-label:'Russia 2018'
application-label-pt:'Russia 2018'
application-label-ca:'Russia 2018'
application-label-da:'Russia 2018'
application-label-fa:'Russia 2018'
application-label-ja:'Russia 2018'
application-label-ka:'Russia 2018'
application-label-pa:'Russia 2018'
application-label-ta:'Russia 2018'
application-label-nb:'Russia 2018'
application-label-be:'Russia 2018'
application-label-de:'Russia 2018'
application-label-ne:'Russia 2018'
application-label-te:'Russia 2018'
application-label-af:'Russia 2018'
application-label-bg:'Russia 2018'
application-label-th:'Russia 2018'
application-label-fi:'Russia 2018'
application-label-hi:'Russia 2018'
application-label-si:'Russia 2018'
application-label-vi:'Russia 2018'
application-label-kk:'Russia 2018'
application-label-mk:'Russia 2018'
application-label-sk:'Russia 2018'
application-label-uk:'Russia 2018'
application-label-el:'Russia 2018'
application-label-gl:'Russia 2018'
application-label-ml:'Russia 2018'
application-label-nl:'Russia 2018'
application-label-pl:'Russia 2018'
application-label-sl:'Russia 2018'
application-label-tl:'Russia 2018'
application-label-am:'Russia 2018'
application-label-km:'Russia 2018'
application-label-bn:'Russia 2018'
application-label-in:'Russia 2018'
application-label-kn:'Russia 2018'
application-label-mn:'Russia 2018'
application-label-ko:'Russia 2018'
application-label-lo:'Russia 2018'
application-label-ro:'Russia 2018'
application-label-sq:'Russia 2018'
application-label-ar:'Russia 2018'
application-label-fr:'Russia 2018'
application-label-hr:'Russia 2018'
application-label-mr:'Russia 2018'
application-label-sr:'Russia 2018'
application-label-sr-Latn:'Russia 2018'
application-label-tr:'Russia 2018'
application-label-ur:'Russia 2018'
application-label-bs:'Russia 2018'
application-label-cs:'Russia 2018'
application-label-es:'Russia 2018'
application-label-is:'Russia 2018'
application-label-ms:'Russia 2018'
application-label-et:'Russia 2018'
application-label-it:'Russia 2018'
application-label-lt:'Russia 2018'
application-label-eu:'Russia 2018'
application-label-gu:'Russia 2018'
application-label-hu:'Russia 2018'
application-label-ru:'Russia 2018'
application-label-zu:'Russia 2018'
application-label-lv:'Russia 2018'
application-label-sv:'Russia 2018'
application-label-iw:'Russia 2018'
application-label-sw:'Russia 2018'
application-label-hy:'Russia 2018'
application-label-ky:'Russia 2018'
application-label-my:'Russia 2018'
application-label-az:'Russia 2018'
application-label-uz:'Russia 2018'
application-label-bs-BA:'Russia 2018'
application-label-fr-CA:'Russia 2018'
application-label-lo-LA:'Russia 2018'
application-label-en-GB:'Russia 2018'
application-label-bn-BD:'Russia 2018'
application-label-et-EE:'Russia 2018'
application-label-ka-GE:'Russia 2018'
application-label-ky-KG:'Russia 2018'
application-label-km-KH:'Russia 2018'
application-label-zh-HK:'Russia 2018'
application-label-si-LK:'Russia 2018'
application-label-mk-MK:'Russia 2018'
application-label-ur-PK:'Russia 2018'
application-label-sq-AL:'Russia 2018'
application-label-hy-AM:'Russia 2018'
application-label-my-MM:'Russia 2018'
application-label-zh-CN:'Russia 2018'
application-label-pa-IN:'Russia 2018'
application-label-ta-IN:'Russia 2018'
application-label-te-IN:'Russia 2018'
application-label-ml-IN:'Russia 2018'
application-label-en-IN:'Russia 2018'
application-label-kn-IN:'Russia 2018'
application-label-mr-IN:'Russia 2018'
application-label-gu-IN:'Russia 2018'
application-label-mn-MN:'Russia 2018'
application-label-ne-NP:'Russia 2018'
application-label-pt-BR:'Russia 2018'
application-label-gl-ES:'Russia 2018'
application-label-eu-ES:'Russia 2018'
application-label-is-IS:'Russia 2018'
application-label-es-US:'Russia 2018'
application-label-pt-PT:'Russia 2018'
application-label-en-AU:'Russia 2018'
application-label-zh-TW:'Russia 2018'
application-label-be-BY:'Russia 2018'
application-label-ms-MY:'Russia 2018'
application-label-az-AZ:'Russia 2018'
application-label-kk-KZ:'Russia 2018'
application-label-uz-UZ:'Russia 2018'
application-icon-120:'res/mipmap-mdpi-v4/ic_launcher.png'
application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
application-icon-213:'res/mipmap-hdpi-v4/ic_launcher.png'
application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
application-icon-65534:'res/mipmap-mdpi-v4/ic_launcher.png'
application: label='Russia 2018' icon='res/mipmap-mdpi-v4/ic_launcher.png' banner='res/mipmap-hdpi-v4/tv_banner.png'
launchable-activity: name='Russia2018.view.activity.SplashActivity'  label='' icon=''
leanback-launchable-activity: name='Russia2018.view.activity.SplashActivity'  label='' icon='' banner=''
feature-group: label=''
  uses-feature-not-required: name='android.hardware.microphone'
  uses-feature-not-required: name='android.hardware.touchscreen'
  uses-feature-not-required: name='android.software.leanback'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
provides-component:'search'
main
other-activities
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'pt' 'ca' 'da' 'fa' 'ja' 'ka' 'pa' 'ta' 'nb' 'be' 'de' 'ne' 'te' 'af' 'bg' 'th' 'fi' 'hi' 'si' 'vi' 'kk' 'mk' 'sk' 'uk' 'el' 'gl' 'ml' 'nl' 'pl' 'sl' 'tl' 'am' 'km' 'bn' 'in' 'kn' 'mn' 'ko' 'lo' 'ro' 'sq' 'ar' 'fr' 'hr' 'mr' 'sr' 'sr-Latn' 'tr' 'ur' 'bs' 'cs' 'es' 'is' 'ms' 'et' 'it' 'lt' 'eu' 'gu' 'hu' 'ru' 'zu' 'lv' 'sv' 'iw' 'sw' 'hy' 'ky' 'my' 'az' 'uz' 'bs-BA' 'fr-CA' 'lo-LA' 'en-GB' 'bn-BD' 'et-EE' 'ka-GE' 'ky-KG' 'km-KH' 'zh-HK' 'si-LK' 'mk-MK' 'ur-PK' 'sq-AL' 'hy-AM' 'my-MM' 'zh-CN' 'pa-IN' 'ta-IN' 'te-IN' 'ml-IN' 'en-IN' 'kn-IN' 'mr-IN' 'gu-IN' 'mn-MN' 'ne-NP' 'pt-BR' 'gl-ES' 'eu-ES' 'is-IS' 'es-US' 'pt-PT' 'en-AU' 'zh-TW' 'be-BY' 'ms-MY' 'az-AZ' 'kk-KZ' 'uz-UZ'
densities: '120' '160' '213' '240' '320' '480' '640' '65534'
native-code: 'arm64-v8a' 'armeabi' 'armeabi-v7a' 'x86' 'x86_64'
 
 
[07:16:05.215] Application name: "Russia 2018" 
[07:16:05.215] Application version code: "10" 
[07:16:05.215] Application version name: "4.1.5" 
[07:16:05.747] JRE (32-bit) version: 1.8.0_151 
[07:16:05.748] JDK (32-bit) version: --- 
[07:16:05.748] Apktool version: 2.2.2 
 
[07:16:05.748] java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

[07:16:07.141] Updater: v1.7.1
 
[07:16:46.938] Unpacked in 41.722s 
[07:16:46.939] Icons: ("res/mipmap-mdpi-v4/ic_launcher.png", "res/mipmap-mdpi-v4/ic_launcher.png", "res/mipmap-hdpi-v4/ic_launcher.png", "res/mipmap-xhdpi-v4/ic_launcher.png", "res/mipmap-xxhdpi-v4/ic_launcher.png", "res/mipmap-xxxhdpi-v4/ic_launcher.png", "res/mipmap-hdpi-v4/tv_banner.png") 
[07:16:47.008] Done.
 
[07:16:47.013] Warning: QPixmap::scaled: Pixmap is a null pixmap
[07:16:56.678] Warning (Icon Missing): This APK does not support current DPI.

**Comment by egymummy** [comment]
this is From APKtool V2.3.1

I: Using Apktool 2.3.1 on t.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: file
must be a directory: t
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:22
7)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: file must be a directory: t
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:20
7)

any Idea ??

**Comment by ibuprophen1** [comment]
Typically (in most cases) :

"QPixmap::scaled: Pixmap is a null pixmap"

Indicates that it cannot load the icons (for various reasons).

**Comment by kefir500** [comment]
@egymummy I sent you email on February 24 and asked you to attach the APK.  
Closing the issue due to inactivity. Reopen if needed.
