### ISSUE TITLE
Ability to Add Other Standard Android Icon Sizes

### ISSUE THREAD

**Issue by ibuprophen1** [kefir500/apk-icon-editor#64]
I'm sure that your aware of this but, I was wondering is you had any plans to expand the Icon Sizes for the Android Selection besides the "TV" option from the list. One of the standard android sizes is 192x192 but, it's not an option to add.

The following are 2 screenshot examples from one of my developments that I used to also reflect the missing 192x192 standard size...

Example 1 - Reflects the TV option being the only one available under the "Android Category".
[example-1](https://user-images.githubusercontent.com/18060271/37843409-b3901d88-2ebc-11e8-9e91-a75e6b3eb40f.png)

Example 2 - Reflects all the categories but, none of them are for the standard Android Sizes.
[example-2](https://user-images.githubusercontent.com/18060271/37843416-bd831de0-2ebc-11e8-83fc-600869eae03d.png)

I'm not stating that this is a show stopper and I know how to manually add the icon's but, this added option could cut down on approx. half of the work for adding 1 or more standard icon size(s).

Thank you very much My Friend! :-) 

~Ibuprophen

**Comment by kefir500** [comment]
Implemented in a2a38d2.
The feature will be presented in 2.0.0 release.
