### ISSUE TITLE
Apktool Selection Feature Request... 

### ISSUE THREAD

**Issue by ibuprophen1** [kefir500/apk-icon-editor#69]
@kefir500, it would be great if there was a way to be able to update/add the Apktool.jar file without having to rename it. 

For example... Keeping the latest Apktool download name "apktool_2.3.3.jar" instead of renaming it to "apktool.jar". 

I ask this because sometimes there may be an issue with a new Apktool release that would possibly require having to revert back a release or two. 

An idea could be to have a separate Apktool directory (inside where its located now) and having multiple releases within it. Then within the settings of the software, being able to either have a drop down list box to select which one to use OR have a button selection that will browse to the Apktool directory to select the version to use. 

I hope that I had explained this okay via text... :-) 

If you need a more visual example, i can create a few example custom images to give you the general idea. 

Thank you very much My Friend! 

~Ibuprophen

**Comment by ibuprophen1** [comment]
@kefir500, I had thought of this idea when I use the APK Easy Tool software (my alternative). If you were to check it out, you may be able to obtain a sense of how it works and, hopefully, what makes it work.

**Comment by kefir500** [comment]
Implemented in 54b945d.
Option to specify custom path to Apktool will be included in the 2.1.0 release.
