### ISSUE TITLE
Ability to cancel the repacking process

### ISSUE THREAD

**Issue by ibuprophen1** [kefir500/apk-icon-editor#71]
This has been something that has always been unavailable but, I just remembered to grab a good screenshot reflecting this. 

Say that you accidentally select the wrong apk to decompile and you just want to cancel the process but, you can't.

The Cancel button has always been there and has always been grey'd out... 

Please see the attached screenshot and you'll see what I'm referring to. 

[apk-icon-editor_example](https://user-images.githubusercontent.com/18060271/40202989-c56c8432-59f1-11e8-8db1-618c647f258d.png)

Thank you very much! :-) 

~Ibuprophen

**Comment by kefir500** [comment]
Implemented in:

- 0e3525e (Ability to cancel the **unpacking** process)
- c29a48e (Ability to cancel the **packing** process)

Feature will be included in the 2.1.0 release.
