### ISSUE TITLE
[Feature Request]  Changing APK Permission

### ISSUE THREAD

**Issue by RyanBram** [kefir500/apk-icon-editor#73]
Hi.
Thank you for this great software.

Currently I am in learning for developing HTML5 games for Android using Cordova. I am using Cordova standard build command.

If you don't mind, is it possible to add feature to make editing permission become easier and more intuitive using GUI?

Thanks.

**Comment by kefir500** [comment]
Hi,
Sorry for the delay.
Thanks for your feedback!

I decided to keep APK Icon Editor simple and stick to its initial goals and title, and created a separate tool for an advanced APK editing – [APK Editor Studio](https://qwertycube.com/apk-editor-studio/). See [this post](https://qwertycube.com/apk-editor-studio/blog/apk-editor-studio-vs-apk-icon-editor/) for more information.

APK Editor Studio v1.3.0 was released a day ago, and now it includes the Permission Editor.
