### ISSUE TITLE
Quick Question... 

### ISSUE THREAD

**Issue by ibuprophen1** [kefir500/apk-icon-editor#76]
@kefir500, I was just wondering if you were aware of the https://github.com/iBotPeaches/Apktool/issues/1897#issuecomment-419705526 from iBotPeaches? 

If you were, I'll just note it as a confirmation... :-) 

~Ibuprophen

**Comment by ibuprophen1** [comment]
I'm going to close this topic as a disinterested topic from the developer... 


~Ibuprophen

**Comment by kefir500** [comment]
Sorry for the delay, I was working on another project.

Thanks for the heads-up, the **Requirements** section on the website was updated, as well as the `README.md` file in the `2.2.0` branch.
