### ISSUE TITLE
me da error al tratar de editar un apk que tiene versión 142

### ISSUE THREAD

**Issue by mahin96** [kefir500/apk-icon-editor#77]
estoy tratando de cambiar el icono a un apk pero al tener una versión avanzada me da un error y este programa   es muy bueno APK Icon Editor pero creo que hay que hacer mejoras en el ya que las nuevas versiones tiene diferentes cosas gracias

**Comment by kefir500** [comment]
Currently it's unclear what your issue is. Please, post your question in English.
