### ISSUE TITLE
Apktool error

### ISSUE THREAD

**Issue by samuelmoiwa** [kefir500/apk-icon-editor#82]
Hi, when I switch from zip mood to apktool mood. The app keeps sending me error. “apktool error”.
I need your help please.

**Comment by kefir500** [comment]
Hi @samuelmoiwa,

1. ZIP mode was deprecated and removed in APK Icon Editor v2.0.0, so I assume you are using the outdated version. Please, [download](https://qwertycube.com/apk-icon-editor/download/) the latest APK Icon Editor (v2.2.0 at the time of writing).
2. Also, please attach the log which can be found in "Help" —> "Logs" menu after you repeat the steps to reproduce this error.

**Comment by kefir500** [comment]
Discussion moved to #83.
