### ISSUE TITLE
Can't download binaries for installation.

### ISSUE THREAD

**Issue by Fabxx** [kefir500/apk-icon-editor#85]
While opening the links in the release section, the browser can't find the URL page. As well as this site: https://qwertycube.com/apk-icon-editor/download/

**Comment by Ibuprophen** [comment]
I just opened that link and it took me to the download location of the website to choose which software to download (Win/Mac). 

I wonder if this is an unfinished feature that was inadvertently overlooked. 


~Ibuprophen

**Comment by kefir500** [comment]
@FabxBs Probably I'm missing the point. Do you mean the GitHub Releases section? Just checked it: all links are working fine. Is there any chance your ISP is blocking the `amazonaws.com` where GitHub stores the downloadable assets?

**Comment by kefir500** [comment]
Closing the issue due to no response.
