### ISSUE TITLE
Unassociate APK file

### ISSUE THREAD

**Issue by AndhikaWB** [kefir500/apk-icon-editor#89]
First of all, thanks for this simple app. Really liked it!

I'm not sure if it's intended or I accidentally clicked the "Associate .APK" from the toolbar but it seems that there is no option to inassociate it again. It would be helpful if you add this option so inexperienced users won't have to inassociate it manually (e.g. by editing registry).

**Comment by kefir500** [comment]
Hi, thanks a lot for your feedback!

Implemented the ability to remove file association in 3912330.
The feature will be present in the upcoming release.
